dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"
matrix:
  include:
  - python: 3.7
    dist: xenial
  - python: 3.8
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls; fi
script: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run --source=google setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: tTFp3yZ3klYAyiV/eYpXHMu+vO3rE229YhES6c5IpytrsssrgEeSM9ixNx7QRYv9mGGFFVDfpqN86qJaRryNuBmpcZCWlNSPXso8ZNWVfZ1WBFnyO/PSKHRsX2oySY+CAv9l5bDKFlibZYUpp6mGXWjl1TLhc8vwVXAqvLlYQ1Q=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
